// <auto-generated />
using System;
using Convertidor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Convertidor.Migrations.DestinoMigrations
{
    [DbContext(typeof(DestinoDataContext))]
    partial class DestinoDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Convertidor.Data.EntitiesDestino.ConceptosRetenciones", b =>
                {
                    b.Property<decimal>("CODIGO_CONCEPTO")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("Titulo")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasDefaultValueSql("('')");

                    b.HasKey("CODIGO_CONCEPTO", "Titulo");

                    b.ToTable("ConceptosRetenciones", (string)null);
                });

            modelBuilder.Entity("Convertidor.Data.EntitiesDestino.HistoricoNomina", b =>
                {
                    b.Property<long>("CODIGO_HISTORICO_NOMINA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CODIGO_HISTORICO_NOMINA"));

                    b.Property<long>("CODIGO_CONCEPTO")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CODIGO_EMPRESA")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CODIGO_PERIODO")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CODIGO_PERSONA")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CODIGO_TIPO_NOMINA")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("COMPLEMENTO_CONCEPTO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EXTRA1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EXTRA2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EXTRA3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FECHA_INS")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FECHA_NOMINA")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FECHA_UPD")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("FRECUENCIA_ID")
                        .HasColumnType("bigint");

                    b.Property<decimal>("MONTO")
                        .HasColumnType("numeric");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TIPO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("USUARIO_INS")
                        .HasColumnType("bigint");

                    b.Property<long>("USUARIO_UPD")
                        .HasColumnType("bigint");

                    b.HasKey("CODIGO_HISTORICO_NOMINA");

                    b.HasIndex("CODIGO_HISTORICO_NOMINA")
                        .IsUnique()
                        .HasDatabaseName("IDX_CODIGO_HISTORICO_NOMINA");

                    b.HasIndex("CODIGO_EMPRESA", "CODIGO_TIPO_NOMINA", "CODIGO_PERIODO", "CODIGO_PERSONA");

                    b.ToTable("HistoricoNomina", (string)null);
                });

            modelBuilder.Entity("Convertidor.Data.EntitiesDestino.HistoricoPersonalCargo", b =>
                {
                    b.Property<decimal>("CODIGO_EMPRESA")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CODIGO_TIPO_NOMINA")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CODIGO_PERIODO")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CODIGO_PERSONA")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("APELLIDO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("('')");

                    b.Property<decimal>("BANCO_ID")
                        .HasColumnType("numeric(5,0)");

                    b.Property<string>("CARGO_CODIGO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('')");

                    b.Property<decimal>("CEDULA")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CODIGO_CARGO")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CODIGO_ICP")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("CODIGO_ICP_UBICACION")
                        .HasColumnType("numeric(18,4)");

                    b.Property<string>("CODIGO_PROGRAMA")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValueSql("('')");

                    b.Property<decimal>("CODIGO_RELACION_CARGO")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("CODIGO_SECTOR")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("DESCRIPCION_BANCO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("DESCRIPCION_CARGO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("DESCRIPCION_NACIONALIDAD")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("DESCRIPCION_SEXO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("DESCRIPCION_STATUS")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("DESCRIPCION_TIPO_CUENTA")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("EXTRA1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("EXTRA2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("EXTRA3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<DateTime>("FECHA_INGRESO")
                        .HasColumnType("date");

                    b.Property<DateTime>("FECHA_INS")
                        .HasColumnType("date");

                    b.Property<DateTime>("FECHA_NOMINA")
                        .HasColumnType("date");

                    b.Property<DateTime>("FECHA_UPD")
                        .HasColumnType("date");

                    b.Property<string>("FOTO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasDefaultValueSql("('')");

                    b.Property<decimal>("FRECUENCIA_PAGO_ID")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("NACIONALIDAD")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("NO_CUENTA")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("SEXO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("STATUS")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasDefaultValueSql("('')");

                    b.Property<decimal>("SUELDO")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TIPO_CUENTA_ID")
                        .HasColumnType("numeric(5,0)");

                    b.Property<string>("TIPO_NOMINA")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<decimal>("USUARIO_INS")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("USUARIO_UPD")
                        .HasColumnType("numeric(10,0)");

                    b.HasKey("CODIGO_EMPRESA", "CODIGO_TIPO_NOMINA", "CODIGO_PERIODO", "CODIGO_PERSONA");

                    b.HasIndex("CODIGO_ICP");

                    b.ToTable("HistoricoPersonalCargo", (string)null);
                });

            modelBuilder.Entity("Convertidor.Data.EntitiesDestino.HistoricoRetenciones", b =>
                {
                    b.Property<long>("CODIGO_HISTORICO_NOMINA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("CODIGO_HISTORICO_NOMINA"));

                    b.Property<string>("APELLIDO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CEDULA")
                        .HasColumnType("integer");

                    b.Property<string>("DESCRIPCION_CARGO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FECHA_INGRESO")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FECHA_INS")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FECHA_NOMINA")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("MONTO")
                        .HasColumnType("numeric");

                    b.Property<string>("NACIONALIDAD")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NOMBRE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SUELDO")
                        .HasColumnType("numeric");

                    b.Property<int>("TIPO_NOMINA")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UNIDAD_EJECUTORA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CODIGO_HISTORICO_NOMINA");

                    b.ToTable("HistoricoRetenciones", (string)null);
                });

            modelBuilder.Entity("Convertidor.Data.EntitiesDestino.IndiceCategoriaPrograma", b =>
                {
                    b.Property<decimal>("CODIGO_ICP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("ANO")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("CODIGO_ACTIVIDAD")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValueSql("('')");

                    b.Property<int>("CODIGO_EMPRESA")
                        .HasColumnType("integer");

                    b.Property<decimal>("CODIGO_FUNCIONARIO")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("CODIGO_OFICINA")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValueSql("('')");

                    b.Property<decimal>("CODIGO_PRESUPUESTO")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("CODIGO_PROGRAMA")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("CODIGO_PROYECTO")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("CODIGO_SECTOR")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("CODIGO_SUBPROGRAMA")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("DENOMINACION")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("DESCRIPCION")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasDefaultValueSql("('')");

                    b.Property<decimal>("ESCENARIO")
                        .HasColumnType("numeric(10,0)");

                    b.Property<string>("EXTRA1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("EXTRA2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<string>("EXTRA3")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValueSql("('')");

                    b.Property<DateTime>("FECHA_FIN")
                        .HasColumnType("date");

                    b.Property<DateTime>("FECHA_INI")
                        .HasColumnType("date");

                    b.Property<DateTime>("FECHA_INS")
                        .HasColumnType("date");

                    b.Property<DateTime>("FECHA_UPD")
                        .HasColumnType("date");

                    b.Property<string>("UNIDAD_EJECUTORA")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValueSql("('')");

                    b.Property<decimal>("USUARIO_INS")
                        .HasColumnType("numeric(10,0)");

                    b.Property<decimal>("USUARIO_UPD")
                        .HasColumnType("numeric(10,0)");

                    b.HasKey("CODIGO_ICP");

                    b.ToTable("IndiceCategoriaPrograma", (string)null);
                });

            modelBuilder.Entity("Convertidor.Data.EntitiesDestino.HistoricoNomina", b =>
                {
                    b.HasOne("Convertidor.Data.EntitiesDestino.HistoricoPersonalCargo", "Codigo")
                        .WithMany("HistoricoNomina")
                        .HasForeignKey("CODIGO_EMPRESA", "CODIGO_TIPO_NOMINA", "CODIGO_PERIODO", "CODIGO_PERSONA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_HistoricoNomina_HistoricoPersonalCargo");

                    b.Navigation("Codigo");
                });

            modelBuilder.Entity("Convertidor.Data.EntitiesDestino.HistoricoPersonalCargo", b =>
                {
                    b.HasOne("Convertidor.Data.EntitiesDestino.IndiceCategoriaPrograma", "IndiceCategoriaPrograma")
                        .WithMany("HistoricoPersonalCargo")
                        .HasForeignKey("CODIGO_ICP")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IndiceCategoriaPrograma_HistoricoPersonalCargo");

                    b.Navigation("IndiceCategoriaPrograma");
                });

            modelBuilder.Entity("Convertidor.Data.EntitiesDestino.HistoricoPersonalCargo", b =>
                {
                    b.Navigation("HistoricoNomina");
                });

            modelBuilder.Entity("Convertidor.Data.EntitiesDestino.IndiceCategoriaPrograma", b =>
                {
                    b.Navigation("HistoricoPersonalCargo");
                });
#pragma warning restore 612, 618
        }
    }
}
