version: '3.4'

networks:
  dev:
    driver: bridge

services:
  ossmma-app:
    image: docker.io/library/convertidorimage
    depends_on:
      - app_db
    container_name: convertidorcontainer
    ports:
      - "8081:80"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnectionBM=User Id=BM;Password=BM;Server=app_db;Validate Connection=true;
      - ASPNETCORE_URLS= http://+:80
    networks:
      - dev
    
  app_db:
    image: epiclabs/docker-oracle-xe-11g
    container_name: app_db
    environment:
      - ORACLE_PASSWORD=oracle
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_ENABLE_XDB=true
    ports:
      - "1521:1521"
    restart: always
    volumes:
      - app_data:/home/ossmma/samiaio
    networks:
      - dev

volumes:
  app_data:
